### PR TITLE
CI: AKV RBAC deployment bug - avoid Managed Identity

### LINKED ISSUE #205: Deployment fails with AKV RBAC
Verify step fails
https://github.com/agera-edc/MinimumViableDataspace/runs/7384302037?check_suite_focus=true

```
Status code 403, "{"error":{"code":"Forbidden","message":"Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: appid=fd29669c-a4f5-4225-bb06-506117b34254;oid=d73ce6d5-d4c9-462e-9d04-8260e39fad63;iss=[https://sts.windows.net/***/\r\nAction:](https://sts.windows.net/***//r/nAction:) 'Microsoft.KeyVault/vaults/secrets/readMetadata/action'\r\nResource: '/subscriptions/***/resourcegroups/rg-company2-ag99/providers/microsoft.keyvault/vaults/kvag99company2'\r\nAssignment: (not found)\r\nVault: kvag99company2;location=northeurope\r\n","innererror":{"code":"ForbiddenByRbac"}}}"
[283](https://github.com/agera-edc/MinimumViableDataspace/runs/7384302037?check_suite_focus=true#step:5:284)
    com.azure.core.exception.HttpResponseException: Status code 403, "{"error":{"code":"Forbidden","message":"Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: appid=fd29669c-a4f5-4225-bb06-506117b34254;oid=d73ce6d5-d4c9-462e-9d04-8260e39fad63;iss=[https://sts.windows.net/***/\r\nAction:](https://sts.windows.net/***//r/nAction:) 'Microsoft.KeyVault/vaults/secrets/readMetadata/action'\r\nResource: '/subscriptions/***/resourcegroups/rg-company2-ag99/providers/microsoft.keyvault/vaults/kvag99company2'\r\nAssignment: (not found)\r\nVault: kvag99company2;location=northeurope\r\n","innererror":{"code":"ForbiddenByRbac"}}}"
[284](https://github.com/agera-edc/MinimumViableDataspace/runs/7384302037?check_suite_focus=true#step:5:285)
    	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[285](https://github.com/agera-edc/MinimumViableDataspace/runs/7384302037?check_suite_focus=true#step:5:286)
    	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[286](https://github.com/agera-edc/MinimumViableDataspace/runs/7384302037?check_suite_focus=true#step:5:287)
    	at
```

### PR DESCRIPTION
**Pull request by algattik**
## What this PR changes/adds

Avoid attempting to use Managed Identity for Azure login for test runs

## Why it does that

Ensure correct identity is picked up when running tests. [As reported](https://github.com/orgs/github-community/discussions/20830), a Managed Identity is sometimes unexpectedly attached to GitHub runners.

## Linked Issue(s)

Closes #205 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly?

### CODE REVIEW

**Review by marcgs — APPROVED** [review]

**Comment by marcgs** [comment]
Great job investigating and fixing this one!

**Comment by cpeeyush** [comment]
@algattik Should also report about it on https://github.com/Azure/login/issues ?

File: system-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferIntegrationTest.java [hunk 1]
```diff
@@ -64,7 +64,8 @@ public void transferBlob_success() {
 
     @NotNull
     private BlobServiceClient getBlobServiceClient(String keyVaultName) {
-        var credential = new DefaultAzureCredentialBuilder().build();
+        // Not using AzureCliCredentialBuilder because of agent issue https://github.com/orgs/github-community/discussions/20830
```
Comment (cpeeyush) [inline system-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferIntegrationTest.java]:
```suggestion
        // Not using DefaultAzureCredentialBuilder because of agent issue https://github.com/orgs/github-community/discussions/20830
```

**Review by cpeeyush — APPROVED** [review]
Approved with a small suggestion. Nice find.
