### PR TITLE
Cloud Deployment: Fix MVD cloud deployment health check failure

### LINKED ISSUE #215: MVD cloud deployments failing on health check
## Description

MVD cloud deployments are failing on connector healt check e.g. https://github.com/agera-edc/MinimumViableDataspace/runs/7495295852?check_suite_focus=true

## Current Behavior 

So far, the observation is that sometime Azure Container Instance gets restarted and within this period if health check via curl is performed then we get an error `curl: (56) Recv failure: Connection reset by peer` and here current curl check do not retry even though we have`--retry` flag specified.

## Expected Behavior

curl should retry on intermittent failures as specified.

## Possible fix

Upgrade curl version to 7.71.0 to support option `--retry-all-errors`

### PR DESCRIPTION
**Pull request by cpeeyush**
## What this PR changes/adds

Cloud deployments are failing during health check steps. So far what we have observed that it is due to Azure Container Instance taking longer to start up or getting restarted initially which make the `curl` health check call to fail.

`curl` is supposed to be retyring in such scenario but it doesn't retry in case of a connection is reset by peer (more in the linked issue). To overcome these two things are added in this PR:

- Update Azure Container Instance liveness check probe to give container more time before it is ready for a health check.
- curl request is done now with `--retry-all-errors` flag which retries on more error codes, so it covers the above-mentioned situation when connection is reset by peer. But in order to have this flag available for curl we need to have curl version at least 7.71.0 which is not available on ubuntu-latest runners (20.04 version), that's why we have added a shell script to upgrade curl version for the jobs where it is needed. 

## Further notes

- Didn't found a curl version >=7.71.0 package which we can directly download and use on ubuntu, hence doing the installation from the source.
- Tried to use ubuntu-22.04 runner which has latest curl version, this runner version is in beta right now from GitHub. While using this runner two times we observed terraform and curl check getting stuck in an indefinite loop. Not sure what was causing that but can because of a runner issue as it is in beta. So, to avoid confusion decided not to use it and do curl update manually with 20.04 runner.

## Linked Issue(s)

Links #215 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [x] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly?

### CODE REVIEW

File: deployment/curl-upgrade.sh [hunk 1]
```diff
@@ -0,0 +1,31 @@
+#!/bin/bash
+
+set -euxo pipefail
+
+#Check installed version of Ubuntu
```
Comment (Izzzu) [inline deployment/curl-upgrade.sh]:
```suggestion
# Check installed version of Ubuntu
```

**Review by zeier — APPROVED** [review]
Changes tested on own fork and subscription.
While the health check failed most of the time without the fix, multiple deployments could be conducted successfully with these changes applied.

**Review by chrislomonico — APPROVED** [review]
I have run through this a few times to ensure that the errors have been addressed.  From what IO can see running against my own private azure environment, the issues have been fixed.
A few things to note:
- I run against a fully cleaned azure env with the exception of the app registrations and the enterprise app
- I run the `init`action without issue
- I immediately run the `deploy` action and there is an issue where the ACR is not ready and the container images built in deploy did not all succeed.  
- I cleaned the one image that made it to the ACR and ran deploy again and all succeeded.

Based on this behavior I am led to believe that there can be a delay between creation of the ACR and when it is ready for utilization (deployment to the repositories).  This can be handled with an update to the documentation to indicate that there should be a slight delay between running the `init` and `deploy` actions
